### ISSUE TITLE
RGS: auto install RGS coa when creating a new instance of container

### ISSUE THREAD

**Issue by astirpe** [onesteinbv/addons-container#31] opened 2023-08-29 12:34 UTC
To be implemented: load RGS coa when creating a new instance of container.

This because it seems that this [function](https://github.com/onesteinbv/addons-container/blob/16.0/l10n_nl_rgs/data/account_chart_template_data.xml) does not have any effect when creating a new container instance.

**Comment by astirpe** [comment] 2023-09-01 13:49
With https://github.com/onesteinbv/addons-container/commit/25859222556174e0c8a58d0153733583eabc9917 the RGS is automatically installed when creating a new company.

Still to be implemented a solution for the first (main) company.

**Comment by astirpe** [comment] 2023-09-04 07:44
Auto-install RGS for main company: https://github.com/onesteinbv/addons-container/commit/2e8fa529de3a5ce7eafa1c30f18212489e850e98

**Comment by ThijsvOers** [comment] 2023-09-04 08:13
@astirpe I am not officially working today for Onestein, but I saw that you fixed this issue. I have installed accountancy.install on a fresh database (on https://dev.flavours.k8s.onestein.eu/web). With one small hickup in the installation (I got a concurrent error) I was able to install the module (with the option to choose my website them which also was a bug), and the RGS is immediately installed correctly. 
Next will be to see what happens when I do the creation via the my Curq website. Are these changes already also available there yet?. Anyway, I will close this task for now (e will see if we get the concurrent ipdate error on Curq as well, but I do not expect that)

**Comment by astirpe** [comment] 2023-09-04 08:48
@ThijsvOers yes, it should also work for curq, to be tested..

**Comment by ThijsvOers** [comment] 2023-09-04 09:21
@astirpe I have just applied for a new DB via Curq, the instance was created, but still with the old Chart of accounts. I created a second company, in that cmpany the COA was empty. This is the same testresult as before this latest fix.

**Comment by astirpe** [comment] 2023-09-04 09:31
@ThijsvOers for what I understand from your feedback, it probably means that the code was not updated in curq. I will check with Dennis tomorrow.

**Comment by ThijsvOers** [comment] 2023-09-04 09:46
Yes, this will be probably the cause, I will wait further notice
regards
    On Monday, September 4, 2023 at 11:31:52 AM GMT+2, Andrea Stirpe ***@***.***> wrote:  
 
 


@ThijsvOers for what I understand from your feedback, it probably means that the code was not updated in curq. I will check with Dennis tomorrow.

**Comment by astirpe** [comment] 2023-09-05 09:48
Hi Thijs, 

with the help of Dennis, we updated the code on curq. Is there a possibility for you to check? Not urgent, can also be tomorrow when you are here... 
Thanks! 

Andrea

**Comment by ThijsvOers** [comment] 2023-09-06 08:20
Tested with a fresh install via Curq application and its working correct now

**Closed as completed by ThijsvOers** 2023-09-06 08:20 UTC
Labels: bug, enhancement
